package com.bignerdbranch.android.beatbox01

/**A .wav sound extension*/
private const val WAV = ".wav"

/**
 *  Eventually, you will want the sound files to be played, so it makes sense to have an object responsible for keeping track of the filename,the name the user should see, and any other information related to that sound.
 *@param assetPath: the absolute path to the sound file
 *@param soundId: the Integer ID of the sound generated by the SoundPool
 */
class Sound(val assetPath: String,var soundId: Int? = null) {
    /**
     * The name of the Sound File without the music file extension e.g .wav .mp3 .ogg
     */
    val name = assetPath.split("/").last().removeSuffix(WAV)

}